[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.14"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hardig = "4U2Pgjdq51NXUEDVX4yyFNMdg6PuLHs9ikn9JThkn21p"

[programs.mainnet]
hardig = "4U2Pgjdq51NXUEDVX4yyFNMdg6PuLHs9ikn9JThkn21p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
